@startuml
'https://plantuml.com/use-case-diagram

actor User
actor Admin

User -> (View Transport Options)
User -> (Book Transport)
User -> (Pay for Services)
'User -> (Receive Real-Time Information)
'User -> (Provide Feedback)
'User -> (View Promotions and Discounts)
'User -> (Contact Emergency Services)

Admin -> (Manage Transport Schedules)
'Admin -> (Update Real-Time Information)
'Admin -> (Monitor System Performance)
'Admin -> (Manage User Feedback)
'Admin -> (Manage Promotions and Discounts)

@enduml